### ISSUE TITLE
[regression] output validation fails with 'invalid numeric literal'

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg#229]
https://travis-ci.org/omg-services/hashes/builds/551375374

```
$ output="$(npx omg run --raw digest -a method=sha1 -a data=foo | jq -c .)"
if [ "$output" != '{"method":"sha1","digest":"0BEEC7B5EA3F0FDBC95D0DD47F3C5BC275DA8A33"}' ] ; then echo "$output"; exit 1; fi
parse error: Invalid numeric literal at line 1, column 5
events.js:170
      throw er; // Unhandled 'error' event
      ^
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:71:16)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket.dummyDestroy [as _destroy] (internal/process/stdio.js:11:5)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:72:12)
```

Funnily enough this works locally with:

```
✔ Ran action: `hmac` with output: {
  "method": "sha1",
  "digest": "9F60EE4B05E590A7F3FAC552BFB9D98FA46F78D9"
}
```

**Comment by wilzbach** [comment]
Also appears:
- https://github.com/microservices/d/pull/2
- https://github.com/microservices/go/pull/3
- https://github.com/microservices/node/pull/2
- https://github.com/microservices/java/pull/2
- https://github.com/microservices/python/pull/6
- https://github.com/microservices/ruby/pull/2
- https://github.com/microservices/scala/pull/1
- https://github.com/microservices/python-events/pull/1
- https://github.com/microservices/node-events/pull/1
