### ISSUE TITLE
Health check failed: Error: (HTTP code 409) unexpected

### ISSUE THREAD

**Issue by wilzbach** [microservices/omg#247]
Repo: https://github.com/microservices/rust
Command:

```
$ omg run message -a name=Pete
```

Passes locally. On the CI:

```
Health check failed
(node:7597) UnhandledPromiseRejectionWarning: Error: (HTTP code 409) unexpected - Cannot kill container: dd3f76b8e0e175e86ddb65a7636c92ba088fbdb19fc4534bb502b94960577435: Container dd3f76b8e0e175e86ddb65a7636c92ba088fbdb19fc4534bb502b94960577435 is not running 
    at /home/travis/build/microservices/rust/node_modules/docker-modem/lib/modem.js:257:17
    at getCause (/home/travis/build/microservices/rust/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/home/travis/build/microservices/rust/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/home/travis/build/microservices/rust/node_modules/docker-modem/lib/modem.js:232:14)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
(node:7597) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7597) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

https://travis-ci.com/microservices/rust/builds/119890405

**Comment by Arinono** [comment]
I should have fixed the issue where the CLI throws a 409 because the container is not reachable. But on my side (locally), the service is not working. The health check fails because the container stopped itself, with only `Hello, world!` in the docker logs.
