### ISSUE TITLE
The CLI works with a failing docker image

### ISSUE THREAD

**Issue by Arinono** [microservices/omg#282]
Running an action with the CLI worked whereas the Docker Image is broken.
The issue here is that the CLI shows a working service, which will fail later with storyscript.

I'm currently using the version `1.0.0-alpha4` built with zeit/pkg

```
> docker run -p 5001:5001 arinono/otp
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '/app/node index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}


> oms run -i arinono/otp generate -a secret="***********"
✔ Successfully started Docker container
✔ Healthcheck successful
ℹ Output: "897335"
✔ Ran action 'generate' successfully
```

**Comment by StoryscriptHuman** [comment]
Fixed as of e52719397117af30b4c06db57e37775bbe2a6054
