### ISSUE TITLE
Preparation for v1: Bug hunt

### ISSUE THREAD

**Issue by judepereira** [microservices/omg#284]
Kudos to @StoryScriptAI and @Arinono for rebuilding the OMS CLI and UI. It's already looking good.

For the bug hunt today, we want to make sure that v1 release of this tool is rock solid, and doesn't have any glaring issues. To guide us, let's focus on these items:

## CLI
1. Speed
2. Validation errors are easy to understand and follow
3. Error messages when it comes to the container runtime (eg: Docker) are appropriate, and do not take more than 1 minute to understand. If this is a common problem, the CLI must additionally print/link to the solution

## UI
1. There are no "hanging" buttons/links
2. The content in the UI accurately reflects the actual state as returned from the container runtime (eg: Docker)
3. Fine motor skills are *not* required for any aspect of the UI
4. The UI *does not freeze* at any point - be it a refresh page, or executing an action. There must never be a point where the user is thinking - is something supposed to happen?

### Going about this
The most obvious way for us to experience the CLI and the UI is to use it naturally. We'll split existing services amongst ourselves, and create a few new ones (ideas welcome, must be small and well scoped).

**Comment by judepereira** [comment]
@Arinono: Arinono/validate
@JeanBarriere accuweather
@williammartin 5/6 of his own services
Aditya - awesome
@judepereira - psql

**Comment by judepereira** [comment]
Bugs:
1. Two flags to print the version `-v`, `-V`
2. Print the output of validate when there's an error, instead of just saying so. Aim to indicate what to do next:
```
h2:psql jude$ omg run select
Config file has errors (found at: /Users/jude/developer/omg/psql/microservice.yml)
h2:psql jude$
# What do I do next??
```
3. Don't print a needless stack trace for common errors:
```
Error: Missing environment variables: POSTGRES_DSN
    at getContainer (/Users/jude/.config/yarn/global/node_modules/omg/lib/services/docker/getContainer.js:51:13)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Daemon.start (/Users/jude/.config/yarn/global/node_modules/omg/lib/services/daemon/Daemon.js:74:11)
    at async Object.run (/Users/jude/.config/yarn/global/node_modules/omg/lib/commands/run.js:49:3)
    at async Object.main [as default] (/Users/jude/.config/yarn/global/node_modules/omg/lib/index.js:119:3)
h2:psql jude$ 
```
The error above is about a missing environment variable, the output must rather say:
```
The environment variable POSTGRES_DSN is not specified. Please specify it with -e POSTGRES_DSN=<value>
```

**Comment by JeanBarriere** [comment]
**UI stressed on tabs**: wrong behavior (see snapshot)
![image](https://user-images.githubusercontent.com/11390722/65775920-5d8a9d80-e141-11e9-968b-6db627d85c33.png)
-> should scroll-x

**Comment by judepereira** [comment]
@JeanBarriere also, there's no way to close a tab.

**Comment by williammartin** [comment]
### Issues

```
$ omg validate
Must be ran in a directory with a `Dockerfile` and a `microservice.y[a]ml`
```

Does validate need a Dockerfile?

**Comment by Arinono** [comment]
@judepereira 
> 1. Two flags to print the version `-v`, `-V`

IMO I don't think this is an issue, in fact I think that't the opposite. Python uses `-V` and Node uses `-v` and I always make the mistake when I'm using python.
So the good thing is that the user will never do this mistake, and I don't see and issue supporting both

**Comment by Arinono** [comment]
@williammartin 
> Does validate need a Dockerfile?

I'm pretty sure it doesn't and the check for this files is before any command, which is maybe not a good idea indeed

**Comment by Arinono** [comment]
<img width="589" alt="Screenshot 2019-09-27 at 16 15 53" src="https://user-images.githubusercontent.com/10957531/65776290-1ea91780-e142-11e9-8f1b-211830fa25a1.png">

Could be good to have required attributes already written here

**Comment by Arinono** [comment]
The `Contribute to Github` in the top right corner does nothing

**Comment by adnrs96** [comment]
```
adnrs96@aditya-HP-ENVY-15-Notebook-PC:~/awesome$ omg -a
Usage:  [options] [command]

For more details on the commands below, run `omg `(validate|build|run|subscribe|shutdown)` --help`

Options:
  -V, --version                         output the version number
  -h, --help                            output usage information

Commands:
  validate [options]                    Validate the structure of a `microservice.yml` in the current directory
  build [options]                       Builds the microservice defined by the `Dockerfile`. Image will be tagged with `omg/$gihub_user/$repo_name`, unless the tag flag is given. If no git config present a random string will be used
  run [options] <action>                Run actions defined in your `microservice.yml`. Must be ran in a directory with a `Dockerfile` and a `microservice.yml`
  subscribe [options] <action> <event>  Subscribe to an event defined in your `microservice.yml`. Must be ran in a directory with a `Dockerfile` and a `microservice.yml`
  ui [options]                          Starts to omg-app which monitors your microservice.
  list [options]                        Lists all actions available in microservice.
adnrs96@aditya-HP-ENVY-15-Notebook-PC:~/awesome$ 
```

Something is fishy around the `shutdown` command. It isn't detailed below but mentioned at the top?
Also doing `omg shutdown --help` prints the same help page.

**Comment by JeanBarriere** [comment]
I've checked the UI a bit more:

https://www.loom.com/share/d5e20d92b34343bd85f641214621367e

**Comment by Arinono** [comment]
<img width="1158" alt="Screenshot 2019-09-27 at 16 24 11" src="https://user-images.githubusercontent.com/10957531/65776885-43ea5580-e143-11e9-8a18-4aedea9307ce.png">

**Comment by adnrs96** [comment]
omg build prints out `ℹ Building Docker image` and freezes for a while and at the end spits out the below in a single instance.
```
Step 1/4 : FROM kennethreitz/pipenv
# Executing 3 build trigger
---> Running in 260f72d2e725
+ pipenv install --deploy --system

Installing dependencies from Pipfile.lock (d16108)…
Removing intermediate container 260f72d2e725
---> bdd872716767
Step 2/4 : ENV PYTHONHASHSEED random
---> Running in c6fc230e54bd
Removing intermediate container c6fc230e54bd
---> da02266bef69
Step 3/4 : COPY . /app
---> 8d822fa457a3
Step 4/4 : CMD python3 server.py
---> Running in 4cd53f4fde4a
Removing intermediate container 4cd53f4fde4a
---> 330a9bae61c3
Successfully built 330a9bae61c3
Successfully tagged omg/l2hvbwuvywrucnm5ni9hd2vzb21l:latest
✔ Built Docker image with name: omg/l2hvbwuvywrucnm5ni9hd2vzb21l
```

Feels like it was doing some steps that should have been printed when it began performing those activities but weren't printed really.

**Comment by adnrs96** [comment]
Cursor changes on Action but there is nothing to click
![cursor](https://user-images.githubusercontent.com/17237412/65777538-d39efc80-e161-11e9-9bc5-dae6976b1266.gif)

**Comment by adnrs96** [comment]
Awesome micro service

* `omg run id` What's the delay after running the command.
![delay](https://user-images.githubusercontent.com/17237412/65780818-2976a300-e168-11e9-842b-f94a7f5f673e.gif)

* In the UI, Send button should not be clickable when no action is selected.
![dash](https://user-images.githubusercontent.com/17237412/65781014-86725900-e168-11e9-9d10-8d44314af762.gif)

* No title mentioned for the arguments box
![image](https://user-images.githubusercontent.com/17237412/65781170-c6394080-e168-11e9-8ec1-41b18ecd7006.png)

* Send doesn't work if no argument is present. `awesome` services `id` action doesn't accept args.
![dash](https://user-images.githubusercontent.com/17237412/65781264-f1239480-e168-11e9-9713-253918845128.gif)

**Comment by steelbrain** [comment]
@adnrs96 The delay AFTER running the command is shutting down the container and garbage collecting it. You can ask the CLI to terminate the container with a `ctrl-c` if you don't wanna wait.

**Comment by adnrs96** [comment]
In that case it should explicitly specify it is shutting down the container and `press ctrl + c` to force exit :)

**Comment by StoryScriptAI** [comment]
> > @adnrs96 The delay AFTER running the command is shutting down the container and garbage collecting it. You can ask the CLI to terminate the container with a ctrl-c if you don't wanna wait.
> In that case it should explicitly specify it is shutting down the container and press ctrl + c to force exit :)

It should yes, I'll add that somewhere

**Comment by StoryScriptAI** [comment]
Thanks for the feedback everyone, here's a changelog of what's happened since this bughunt concluded:

-  Action arguments and environment values are now validated before booting up the container
- Action/Env error messages include extra help content to help the user navigate on fix for them
- Typos inside the Environment modal have been fixed
- Environment modal as well as left/right side-bars have been resized to fix bad styles on small screens
- Inherit env option is now supported in `omg run` and `omg subscribe`
- Horizontal scroll and close button have been made functional for tabs
- Empty strings are now correctly recognized as arguments/env values
- Docker/App log is persisted across app refreshes upto 500 lines for both types individually
- Dockerfile existence is no longer required when specifying image in CLI
- Specifying custom image is now supported for `omg ui`
- `omg list` now has a `--pretty` in addition to `--json` for pretty printing the JSON
- Container network errors now look nicer with more helpful info
- CLI now supports JSON-encoded arguments for `map`, `object` and `list` types
- Contribute on Github button now opens a github tab properly
- CLI Errors do not print a stack trace unless `OMS_CLI_DEBUG` var is provided

There's more UI stuff cooking in the oven

**Comment by StoryscriptHuman** [comment]
Here's a tl;dr of what's changed since the last changelog posting:

- `-V` has been removed in favor of `-v`
- Validation bug with nested object args has been fixed for `in`
- Image build failures are detected and reported properly
- Grouping has been removed from actions history
- Actions history now has controls for bookmarking or deleting individual items
- Search for history is now functioning as intended
- Image building is deferred until env vars are input in UI for when there are some required env vars
- Both Env modal and sidebar now shows both Docker and Application logs in reversed order
- Styles of the Actions select have been fixed for different screen sizes
- UX Improvements around the board, especially for areas that have nothing to show
- Send and save buttons are disabled to avoid confusion when no action is selected

More to come soon!
